import Foundation
import CryptoKit

public enum LibraryCategory: String, Codable, CaseIterable, Sendable {
    case sfx, music, overlay, background, texture
    public var displayName: String {
        switch self { case .sfx: return "효과음"; case .music: return "배경음악"; case .overlay: return "장식 · 오버레이"; case .background: return "배경"; case .texture: return "질감" }
    }
}

public struct LibraryAsset: Codable, Identifiable, Equatable, Sendable {
    public var id: String
    public var name: String
    public var category: LibraryCategory
    public var relativePath: String
    public var author: String
    public var sourceURL: String
    public var license: String
    public var licenseURL: String
    public var sha256: String
    public var tags: [String]
    public var duration: Double?
    /// "downloaded" is collected third-party work; "original" is generated by the bundled source scripts.
    public var origin: String?
    public var originalFilename: String?
    public var downloadURL: String?
    public var sourceSHA256: String?
    public var fileBytes: Int64?
    public var width: Int?
    public var height: Int?
    public var bpm: Double?
    public init(id: String, name: String, category: LibraryCategory, relativePath: String, author: String, sourceURL: String, license: String, licenseURL: String, sha256: String, tags: [String] = [], duration: Double? = nil, origin: String? = nil, originalFilename: String? = nil, downloadURL: String? = nil, sourceSHA256: String? = nil, fileBytes: Int64? = nil, width: Int? = nil, height: Int? = nil, bpm: Double? = nil) {
        self.id = id; self.name = name; self.category = category; self.relativePath = relativePath; self.author = author; self.sourceURL = sourceURL; self.license = license; self.licenseURL = licenseURL; self.sha256 = sha256; self.tags = tags; self.duration = duration; self.origin = origin; self.originalFilename = originalFilename; self.downloadURL = downloadURL; self.sourceSHA256 = sourceSHA256; self.fileBytes = fileBytes; self.width = width; self.height = height; self.bpm = bpm
    }
    public var sourceLabel: String { origin == "original" ? "직접 제작" : "외부 CC0 수집" }
}

public enum AssetLibraryError: LocalizedError {
    case missing(String), invalid(String), checksum(String)
    public var errorDescription: String? {
        switch self {
        case .missing(let text): return "소재 라이브러리를 찾을 수 없습니다: \(text)"
        case .invalid(let text): return "소재 목록이 올바르지 않습니다: \(text)"
        case .checksum(let text): return "소재 파일 검증에 실패했습니다: \(text)"
        }
    }
}

/// Fully offline, file-backed asset catalog. manifest.json is a JSON array of LibraryAsset objects.
public struct AssetLibrary: Sendable {
    public let assets: [LibraryAsset]
    public let rootURL: URL
    public init(rootURL: URL? = nil) throws {
        let manager = FileManager.default
        let selected: URL
        if let rootURL { selected = rootURL }
        else {
            let bundled = Bundle.main.resourceURL?.appendingPathComponent("Library", isDirectory: true)
            let local = URL(fileURLWithPath: manager.currentDirectoryPath, isDirectory: true).appendingPathComponent("Resources/Library", isDirectory: true)
            if let bundled, manager.fileExists(atPath: bundled.appendingPathComponent("manifest.json").path) { selected = bundled }
            else { selected = local }
        }
        self.rootURL = selected.standardizedFileURL.resolvingSymlinksInPath()
        let manifest = self.rootURL.appendingPathComponent("manifest.json")
        guard manager.fileExists(atPath: manifest.path) else { throw AssetLibraryError.missing(manifest.path) }
        assets = try JSONDecoder().decode([LibraryAsset].self, from: Data(contentsOf: manifest))
        var identifiers = Set<String>(), paths = Set<String>()
        for asset in assets {
            guard !asset.id.isEmpty, identifiers.insert(asset.id).inserted, paths.insert(asset.relativePath).inserted,
                  !asset.name.isEmpty, !asset.author.isEmpty, !asset.license.isEmpty,
                  asset.sha256.count == 64, asset.sha256.allSatisfy({ $0.isHexDigit }),
                  asset.duration.map({ $0.isFinite && $0 > 0 }) ?? true else { throw AssetLibraryError.invalid(asset.name) }
            _ = try Self.containedURL(relativePath: asset.relativePath, root: self.rootURL)
        }
    }
    public func url(for asset: LibraryAsset) -> URL {
        // Unknown caller-supplied records cannot escape the library directory.
        guard assets.contains(where: { $0.id == asset.id && $0.relativePath == asset.relativePath }),
              let result = try? Self.containedURL(relativePath: asset.relativePath, root: rootURL) else {
            return rootURL.appendingPathComponent("__invalid-library-asset__")
        }
        return result
    }
    public func verify() throws {
        for asset in assets {
            let location = try Self.containedURL(relativePath: asset.relativePath, root: rootURL)
            var isDirectory: ObjCBool = false
            guard FileManager.default.fileExists(atPath: location.path, isDirectory: &isDirectory), !isDirectory.boolValue else { throw AssetLibraryError.missing(asset.relativePath) }
            let handle = try FileHandle(forReadingFrom: location)
            defer { try? handle.close() }
            var digest = SHA256()
            while let data = try handle.read(upToCount: 1_048_576), !data.isEmpty { digest.update(data: data) }
            let actual = digest.finalize().map { String(format: "%02x", $0) }.joined()
            guard actual == asset.sha256.lowercased() else { throw AssetLibraryError.checksum(asset.name) }
        }
    }
    private static func containedURL(relativePath: String, root: URL) throws -> URL {
        let components = relativePath.split(separator: "/", omittingEmptySubsequences: false)
        guard !relativePath.isEmpty, !relativePath.hasPrefix("/"), !relativePath.contains("\\"),
              components.allSatisfy({ !$0.isEmpty && $0 != "." && $0 != ".." }) else { throw AssetLibraryError.invalid("허용되지 않은 경로: \(relativePath)") }
        let candidate = root.appendingPathComponent(relativePath).standardizedFileURL.resolvingSymlinksInPath()
        guard candidate.path.hasPrefix(root.path + "/") else { throw AssetLibraryError.invalid("라이브러리 외부 경로: \(relativePath)") }
        return candidate
    }
}
